config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords' }

  devise_scope :user do
    root to: 'users/sessions#new'
  end

  namespace :admin do
    resources :users
    resources :organizations
    resources :employees
  end

  namespace :superadmin do
    resources :users
    get  '/home', to: 'users#home'
    resources :departments
    resources :organizations
    resources :employees do
      collection do
        get 'get_departments', to: 'employees#get_departments'
      end
    end
  end

  namespace :employee do
    resources :users
    resources :organizations
  end

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  belongs_to :user
  has_many :user_organizations
  has_many :employees, through: :user_organizations
  # accepts_nested_attributes_for :user_organizations
  # def admin_organizations
  #   # p   self.inspect
  #   # if self.has_role?(:admin)
  #      Organization.where(id: self.user_id)
  #   # end
  # end

  has_many :admin_depts, primary_key: :user_id, foreign_key: :user_id
  has_many :departments, through: :admin_depts

end

app/controllers/admin/organizations_controller.rb
class Admin::OrganizationsController < ApplicationController

before_action :set_organization, only: [:edit, :show, :update, :destroy]

    def index
      @organizations = Organization.all
    end

    def create
      @organization = Organization.new(organization_params)
      if @organization.save
        redirect_to admin_organizations_path
      else
        render 'new'
      end
    end

    def show
    end

    def new
      # @organization = Organization.new
      # @users = User.all
      # @users = @users.collect {|user| [user.email, user.id] if user.admin_organization.nil?}.compact
    end

    def edit
    # authorize! :edit, current_user
    #   @users = Admin.all
    #   @users = @users.collect {|user| [user.email, user.id] if user.admin_organization.nil?}.compact
    #   user = @organization.user
    #   @users << ([user.email, user.id])

    end

    def update
       if @organization.update_attributes(organization_params)
         redirect_to admin_organizations_path
       else
         render 'edit'
       end
       authorize! :update, @organization
     end

     def destroy
       @organization.destroy
       redirect_to admin_organizations_path
     end

     private

     def organization_params
       params
       .require(:organization)
       .permit(
         :user_id,
         :name,
         :address,
         :email,
         # department_ids: [],
         # :organization_id
       )
     end

     def set_organization
       @organization = Organization.find(params[:id])
     end

end

app/controllers/employee/organizations_controller.rb
class Employee::OrganizationsController < ApplicationController

  def index
    @employee = Employee.find_by_id(current_user.id)
    @organization = current_user.organization
    @departments = @employee.departments.pluck(:name).join(",")
  end

end

app/controllers/superadmin/organizations_controller.rb
class Superadmin::OrganizationsController < ApplicationController

before_action :set_organization, only: [:edit, :show, :update, :destroy]

    def index
      @organizations = Organization.all
    end

    def create
      @organization = Organization.new(organization_params)
      if @organization.save
        redirect_to superadmin_organizations_path
      else
        render 'new'
      end
    end

    def new
      @organization = Organization.new
      @users = Admin.all
      @users = @users.collect {|user| [user.email, user.id] if user.admin_organization.nil?}.compact
    end

    def edit
      @users = Admin.all
      @users = @users.collect {|user| [user.email, user.id] if user.admin_organization.nil?}.compact
      puts "-----1---#{@users}------------"
      user = @organization.user
      puts "-----2---#{@organization.user}------------"
      @users << ([user.email, user.id])
        puts "----3----#{@users}------------"

    end

    def update
       if @organization.update_attributes(organization_params)
         redirect_to superadmin_organizations_path
       else
         render 'edit'
       end
     end

     def destroy
       @organization.destroy
       redirect_to superadmin_organizations_path
     end

     # def options_for_select
     #   [
     #   [user.email, user.id]
     # ]
     # end

     private

     def organization_params
       params
       .require(:organization)
       .permit(
         :user_id,
         :name,
         :address,
         :email,
         department_ids: [],
         # :organization_id
       )
     end

     def set_organization
       @organization = Organization.find(params[:id])
     end

  end

app/helpers/admin/organizations_helper.rb
module Admin::OrganizationsHelper
end

app/helpers/employee/organizations_helper.rb
module Employee::OrganizationsHelper
end

app/helpers/superadmin/organizations_helper.rb
module Superadmin::OrganizationsHelper
end

app/views/share/organization/_form.html.erb
<% new_record = @organization.new_record? %>
<h1><%= new_record ? "Add Organization" : "Edit Organization" %></h1>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <% button = new_record ? "Add" : "Update" %>
    <% check_role = (current_user.has_role?(:superadmin)) %>
    <% button_cancel = check_role ? superadmin_organizations_path : admin_organizations_path %>
    <% url_superadmin = new_record ? superadmin_organizations_path : superadmin_organization_path %>
    <% url_admin = new_record ? admin_organizations_path : admin_organization_path %>
      <%= form_for(@organization, url: check_role ? url_superadmin : url_admin) do |f| %>

      <%#= render 'shared/error_messages', object: f.object %>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :admin %>
      <% if check_role %>
         <%= f.select :user_id, options_for_select(@users, @organization.user_id), {:prompt => "Please select"}, class: "form-control" %>
      <% else %>
        <%= f.text_field :user_email, :value => current_user.email, :readonly => true, class: "form-control" %>
        <%= f.hidden_field :user_id, :value => current_user.id %>
      <% end %>
    </div>

    <div class="form-group">
      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
    </div>

    <div style="display:inline-block;">
      <%= f.submit button, class: "btn btn-primary" %></div>
      <%= link_to "Cancel", button_cancel, class: "btn btn-primary" %>
    </div>
    <% end %>

  </div>
</div>