config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords' }

  devise_scope :user do
    root to: 'users/sessions#new'
  end

  namespace :admin do
    resources :users
    resources :organizations
    resources :employees
  end

  namespace :superadmin do
    resources :users
    get  '/home', to: 'users#home'
    resources :departments
    resources :organizations
    resources :employees do
      collection do
        get 'get_departments', to: 'employees#get_departments'
      end
    end
  end

  namespace :employee do
    resources :users
    resources :organizations
  end

end

app/models/employee.rb
class Employee < User
  # self.table_name = "users"
  default_scope -> { User.with_role(:employee) }

  has_many :employee_depts, dependent: :destroy
  has_many :departments, through: :employee_depts
  accepts_nested_attributes_for :employee_depts
  # has_many :jobs, foreign_key: "user_id", class_name: "Task"




end

app/controllers/admin/employees_controller.rb
class Admin::EmployeesController < ApplicationController

before_action :set_employee, only: [:edit, :show, :update, :destroy]
# before_action :set_organization, only: [:create]

  def index
    @employees = Employee.all
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      @employee.remove_role :admin
      @employee.add_role :employee
      redirect_to admin_employees_path
    else
      render 'new'
    end
  end

  def new
    @employee = Employee.new
    @employee.build_user_organization
    @employee.employee_depts.build unless @employee.present?
    @admin_org = current_user.admin_organization
  end

  def edit
    @employee.build_user_organization unless @employee.user_organization.present?
    @admin_org = current_user.admin_organization
  end

  def show
  end

  def update
   if @employee.update_attributes(employee_params)
     redirect_to admin_employees_path
   else
     render 'edit'
   end
  end

   def destroy
     @employee.destroy
     redirect_to admin_employees_path
   end




   # def get_departments
   #   @departments = []
   #   @emp = Employee.find(params[:employee_id]) if params[:employee_id].present?
   #   org_id = params[:organization_id]
   #   organization = Organization.find(org_id)
   #   @departments = organization.departments if organization.present?
   #   # render json: @departments
   #   respond_to do |format|
   #     format.js
   #   end
   # end

  private

  def set_employee
    @employee = Employee.find(params[:id])
  end

  def employee_params
    params
      .require(:employee)
      .permit(
              :name,
              :age,
              :country,
              :gender,
              :email,
              :password,
              :password_confirmation,
              # :organization_id,
              user_organization_attributes: [:organization_id, :id],
              department_ids: []
            )
  end

end

app/controllers/employee/organizations_controller.rb
class Employee::OrganizationsController < ApplicationController

  def index
    @employee = Employee.find_by_id(current_user.id)
    @organization = current_user.organization
    @departments = @employee.departments.pluck(:name).join(",")
  end

end

app/controllers/employee/users_controller.rb
class Employee::UsersController < ApplicationController

before_action :authenticate_employee
before_action :set_employee, only: [:edit, :show, :update, :destroy]

  def index
    @users = Employee.all
  end

  def create
  end

  def new
    @employee = Employee.new
  end

  def edit
  end

  def show
  end

  def update
   if @employee.update_attributes(employee_params)
     redirect_to employee_user_path
   else
     render 'edit'
   end
  end

   def destroy
   end

  private

  def authenticate_employee
    unless current_user.has_role? :employee
      redirect_to root_path
    end
  end

  def set_employee
    @employee = Employee.find(params[:id])
  end

  def employee_params
    params
      .require(:employee)
      .permit(
              :name,
              :age,
              :country,
              :gender,
              :email,
              :password,
              :password_confirmation,
              user_organization_attributes: [:organization_id, :id],
              department_ids: []
              # departments_attributes: [:id, department_id: []]
              # employee_dept_attributes: [:id, :department_id]
            )
  end

end

app/controllers/superadmin/employees_controller.rb
class Superadmin::EmployeesController < ApplicationController

    before_action :set_employee, only: [:edit, :show, :update, :destroy]
    # after_action :assign_default_role, only: [:create]

    def index
      @employees = Employee.all
    end

    def create
      @employee = Employee.new(employee_params)
      if @employee.save
        @employee.remove_role :admin
        @employee.add_role :employee
        redirect_to superadmin_employees_path
      else
        render 'new'
      end
    end

    def new
      @employee = Employee.new
      @employee.build_user_organization
      @employee.employee_depts.build unless @employee.present?
    end

    def edit
      @employee.build_user_organization unless @employee.user_organization.present?
    end

    def show
    end

    def update
     if @employee.update_attributes(employee_params)
       redirect_to superadmin_employees_path
     else
       render 'edit'
     end
    end

     def destroy
       @employee.destroy
       redirect_to superadmin_employees_path
     end

     def get_departments
       @departments = []
       @emp = Employee.find(params[:employee_id]) if params[:employee_id].present?
       org_id = params[:organization_id]
       organization = Organization.find(org_id)
       @departments = organization.departments if organization.present?
       # render json: @departments
       respond_to do |format|
         format.js
       end
     end
       # if organization.present?
       #   user_id = organization.user_id
       #   admin_depts = AdminDept.where(user_id: user_id)
       #   if admin_depts.present?
       #     admin_depts.each do |dept|
       #       dep_id = dept.department_id
       #       tmp_department = Department.find(dep_id)
       #       @departments << {'department_name': tmp_department.name, 'department_id':tmp_department.id}
       #     end
       #     # puts "------------------------ #{@departments}"
       #   # else
       #     # puts "-------------------------- No admin depts present"
       #   end
       # # else
       #   # puts "-------------------------- No organization present"
       # end

      #  respond_to do |format|
      #   format.js
      # end



    private

    def set_employee
      @employee = Employee.find(params[:id])
    end

    # def assign_default_role
    #   self.add_role(:employee) if self.role.blank?
    # end

    def employee_params
      params
        .require(:employee)
        .permit(
                :name,
                :age,
                :country,
                :gender,
                :email,
                :password,
                :password_confirmation,
                user_organization_attributes: [:organization_id, :id],
                department_ids: []
                # departments_attributes: [:id, department_id: []]
                # employee_dept_attributes: [:id, :department_id]
              )
    end

  end

app/helpers/admin/employees_helper.rb
module Admin::EmployeesHelper
end

app/helpers/employee/organizations_helper.rb
module Employee::OrganizationsHelper
end

app/helpers/employee/users_helper.rb
module Employee::UsersHelper
end

app/helpers/superadmin/employees_helper.rb
module Superadmin::EmployeesHelper
end

app/views/share/employee/_form.html.erb
<% new_record = @employee.new_record? %>
<% @check_role = current_user.has_role?(:superadmin) %>
<% button = new_record ? "Add" : "Update" %>
<% button_cancel = @check_role ? superadmin_employees_path : admin_employees_path %>
<% url_superadmin = new_record ? superadmin_employees_path : superadmin_employee_path %>
<% url_admin = new_record ? admin_employees_path : admin_employee_path %>

  <%= form_for(@employee, url: @check_role ? url_superadmin : url_admin) do |f| %>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :age %>
      <%= f.text_field :age, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :country %>
      <%= f.select :country, %w{India USA Canada}, {:prompt => 'Select Country'}, required: true, placeholder: 'Country', class: 'form-control' %>
    </div>

    <div class="form-group">
    <div class="row">
      <div class="col-md-12 nopadding">
        <div class="col-md-2 nopadding">
          <label class="btn">
            <%= f.label :gender, 'Gender :' %>
          </label>
        </div>
        <div class="col-md-2 nopadding">
          <label class="btn">
            <%= f.radio_button :gender, 'Male', class: 'inline-block' %>
            <%= f.label :gender, 'Male' %>
          </label>
        </div>
        <div class="col-md-2 nopadding">
          <label class="btn">
            <%= f.radio_button :gender, 'Female', class: 'inline-block' %>
            <%= f.label :gender, 'Female' %>
          </label>
        </div>
        <div class="col-md-2">
          <label class="btn">
            <%= f.radio_button :gender, 'Other', class: 'inline-block' %>
            <%= f.label :gender, 'Other' %>
          </label>
        </div>
      </div>
    </div>
    </div>

    <% if @check_role %>
      <div class="form-group" id='xyz'>
        <%= f.label :organization %>
          <%= f.fields_for :user_organization do |u| %>
            <%= u.collection_select :organization_id, Organization.all, :id, :name, {}, class: "form-control" %>
          <% end %>
        </div>
    <% else %>
      <%= f.fields_for :user_organization do |u| %>
        <%= u.hidden_field :organization_id, :value => @admin_org.id %>
      <% end %>
    <% end %>

    <div class="form-group">
      <%= label :department, "Department : " %>
      <% if @check_role %>
        <div class="checkbox">
        </div>
      <% else %>
        <% current_user.departments.all.each do |d| %>
          <div class="checkbox">
           <%= check_box_tag "employee[department_ids][]", d.id, @employee.department_ids.include?(d.id) %>
           <%= d.name %>
          </div>
        <% end %>
      <% end %>
    </div>

    <div class="form-group">
      <%= f.label :"email" %>
      <%= f.email_field :email, class: 'form-control' %>
    </div>

    <% if @employee.new_record? %>
      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, "Confirm Password" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
    <% end %>

    <div style="display:inline-block;">
    <%= f.submit button, class: "btn btn-primary btn-md" %></div>
    <%= link_to "Cancel", button_cancel , class: "btn btn-primary btn-md" %>

<% end %>