config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords' }

  devise_scope :user do
    root to: 'users/sessions#new'
  end

  namespace :admin do
    resources :users
    resources :organizations
    resources :employees
  end

  namespace :superadmin do
    resources :users
    get  '/home', to: 'users#home'
    resources :departments
    resources :organizations
    resources :employees do
      collection do
        get 'get_departments', to: 'employees#get_departments'
      end
    end
  end

  namespace :employee do
    resources :users
    resources :organizations
  end

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  belongs_to :user
  has_many :user_organizations
  has_many :employees, through: :user_organizations
  # accepts_nested_attributes_for :user_organizations
  # def admin_organizations
  #   # p   self.inspect
  #   # if self.has_role?(:admin)
  #      Organization.where(id: self.user_id)
  #   # end
  # end

  has_many :admin_depts, primary_key: :user_id, foreign_key: :user_id
  has_many :departments, through: :admin_depts

end

app/controllers/admin/organizations_controller.rb
class Admin::OrganizationsController < ApplicationController

before_action :set_organization, only: [:edit, :show, :update, :destroy]

    def index
      @organizations = Organization.all
    end

    def create
      @organization = Organization.new(organization_params)
      if @organization.save
        redirect_to admin_organizations_path
      else
        render 'new'
      end
    end

    def show
    end

    def new
      # @organization = Organization.new
      # @users = User.all
      # @users = @users.collect {|user| [user.email, user.id] if user.admin_organization.nil?}.compact
    end

    def edit
    # authorize! :edit, current_user
    #   @users = Admin.all
    #   @users = @users.collect {|user| [user.email, user.id] if user.admin_organization.nil?}.compact
    #   user = @organization.user
    #   @users << ([user.email, user.id])

    end

    def update
       if @organization.update_attributes(organization_params)
         redirect_to admin_organizations_path
       else
         render 'edit'
       end
       authorize! :update, @organization
     end

     def destroy
       @organization.destroy
       redirect_to admin_organizations_path
     end

     private

     def organization_params
       params
       .require(:organization)
       .permit(
         :user_id,
         :name,
         :address,
         :email,
         # department_ids: [],
         # :organization_id
       )
     end

     def set_organization
       @organization = Organization.find(params[:id])
     end

end

app/controllers/employee/organizations_controller.rb
class Employee::OrganizationsController < ApplicationController

  def index
    @employee = Employee.find_by_id(current_user.id)
    @organization = current_user.organization
    @departments = @employee.departments.pluck(:name).join(",")
  end

end

app/controllers/superadmin/organizations_controller.rb
class Superadmin::OrganizationsController < ApplicationController

before_action :set_organization, only: [:edit, :show, :update, :destroy]

    def index
      @organizations = Organization.all
    end

    def create
      @organization = Organization.new(organization_params)
      if @organization.save
        redirect_to superadmin_organizations_path
      else
        render 'new'
      end
    end

    def new
      @organization = Organization.new
      @users = Admin.all
      @users = @users.collect {|user| [user.email, user.id] if user.admin_organization.nil?}.compact
    end

    def edit
      @users = Admin.all
      @users = @users.collect {|user| [user.email, user.id] if user.admin_organization.nil?}.compact
      puts "-----1---#{@users}------------"
      user = @organization.user
      puts "-----2---#{@organization.user}------------"
      @users << ([user.email, user.id])
        puts "----3----#{@users}------------"

    end

    def update
       if @organization.update_attributes(organization_params)
         redirect_to superadmin_organizations_path
       else
         render 'edit'
       end
     end

     def destroy
       @organization.destroy
       redirect_to superadmin_organizations_path
     end

     # def options_for_select
     #   [
     #   [user.email, user.id]
     # ]
     # end

     private

     def organization_params
       params
       .require(:organization)
       .permit(
         :user_id,
         :name,
         :address,
         :email,
         department_ids: [],
         # :organization_id
       )
     end

     def set_organization
       @organization = Organization.find(params[:id])
     end

  end

app/helpers/admin/organizations_helper.rb
module Admin::OrganizationsHelper
end

app/helpers/employee/organizations_helper.rb
module Employee::OrganizationsHelper
end

app/helpers/superadmin/organizations_helper.rb
module Superadmin::OrganizationsHelper
end

app/views/admin/organizations/edit.html.erb
<%= render "share/organization/form" %>

app/views/admin/organizations/index.html.erb
<h1>Organization List</h1>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <!-- <p align="right"><%#= link_to "New Organization", new_admin_organization_path, class: "btn btn-primary" %></p> -->
      <table id="organizations" class="table table-hover">
    	<thead class="thead-dark">
    		<tr>
    			<th>Name</th>
          <th>Admin</th>
          <th>Address</th>
          <th>Email</th>
          <th colspan="2">Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @organizations.each do |organization| %>
        <tr>
          <% organization_user = organization.user %>
          <td><%= organization.name %></td>
          <td><%= organization_user.present? ? organization_user.email : "-" %></td>
          <td><%= organization.address %></td>
          <td><%= organization.email %></td>

          <!-- <td><%#= link_to "show", superadmin_department_path(user) %></td> -->
          <% if current_user == organization_user %>
            <td><%= link_to "Edit", edit_admin_organization_path(organization) if can? :update, Organization %></td>
          <% else %>
            <td><%= link_to "Show", admin_organization_path(organization)  %></td>
          <% end %>
          <!-- <td><%#= link_to "Destroy", admin_organization_path(organization), method: :delete, data: { confirm: "Are you sure?" } %></td> -->
        </tr>
        <% end %>
      </tbody>
    </table>


</div>
</div>

app/views/admin/organizations/show.html.erb
<h1>Organization</h1>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
		<table class="table table-hover">
      <thead class="thead-dark">
				<tr>
          <td class="tbl_head">Column</td>
          <td class="tbl_head">Value</td>
        </tr>
      </thead>
      <tbody class="thead-light">
        <tr>
          <td><%= label :name, "Name", class: "tbl_label" %></td>
          <td><%= label :name, @organization.name, class: "tbl_label" %></td>
        </tr>
        <tr>
          <td><%= label :admin, "Admin", class: "tbl_label" %></td>
          <td><%= label :address, @organization.user.try(:email), class: "tbl_label" %></td>
        </tr>
        <tr>
          <td><%= label :address, "Address", class: "tbl_label" %></div>
          <td><%= label :address, @organization.address, class: "tbl_label" %></div>
        </tr>
        <tr>
          <td><%= label :email, "Email", class: "tbl_label" %></td>
          <td><%= label :email, @organization.email, class: "tbl_label" %></td>
        </tr>
		  </tbody>
		</table>
    <p align="right"><%= link_to "Back", admin_organizations_path, class: "btn btn-primary" %></p>
	</div>
</div>