config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords' }

  devise_scope :user do
    root to: 'users/sessions#new'
  end

  namespace :admin do
    resources :users
    resources :organizations
    resources :employees
  end

  namespace :superadmin do
    resources :users
    get  '/home', to: 'users#home'
    resources :departments
    resources :organizations
    resources :employees do
      collection do
        get 'get_departments', to: 'employees#get_departments'
      end
    end
  end

  namespace :employee do
    resources :users
    resources :organizations
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  has_many :admin_depts, dependent: :destroy, foreign_key: :user_id
  has_many :departments, through: :admin_depts
  accepts_nested_attributes_for :admin_depts

  has_one :user_organization
  has_one :organization, through: :user_organization
  accepts_nested_attributes_for :user_organization

  has_one :admin_organization, class_name: "Organization", foreign_key: :user_id

  # scope :admin, -> { order("name") }
  # scope :employee, -> { order("id") }

  after_create :assign_default_role
  attr_accessor :department_id
  validates :name, presence: true, length: { maximum: 50 }
  validates :age, numericality: { only_integer: true }
  validates :country, :presence => true

  enum gender: [:Male, :Female, :Other]
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  # def admin_organizations
  #   p   self.inspect
  #   if self.has_role?(:admin)
  #     Organization.where(user_id: self.id)
  #   end
  # end
  def admin?
    self.has_role?(:admin)
  end


  def assign_default_role
    self.add_role(:admin) if self.roles.blank?
  end
  #
  # def add_field
  #   if @user.has_role? :employee
  #     add_reference :users, :organization, foreign_key: true
  #   end
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_action :authenticate_admin
  before_action :set_user_admin, only: [:edit, :show, :update, :destroy]

  def index
  end

  def create
  end

  def new
    @user = User.new
  end

  def edit
  end

  def show
  end

  def update
     if @user.update_attributes(user_params)
       redirect_to admin_user_path
     else
       render 'edit'
     end
  end

  

  # def destroy
  #   User.find(params[:id]).destroy
  #   redirect_to superadmin_users_path
  # end

  private

  def authenticate_admin
    unless current_user.has_role? :admin
      redirect_to root_path
    end
  end

  def set_user_admin
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :age, :country, :gender, :email)
  end


end

app/controllers/employee/users_controller.rb
class Employee::UsersController < ApplicationController

before_action :authenticate_employee
before_action :set_employee, only: [:edit, :show, :update, :destroy]

  def index
    @users = Employee.all
  end

  def create
  end

  def new
    @employee = Employee.new
  end

  def edit
  end

  def show
  end

  def update
   if @employee.update_attributes(employee_params)
     redirect_to employee_user_path
   else
     render 'edit'
   end
  end

   def destroy
   end

  private

  def authenticate_employee
    unless current_user.has_role? :employee
      redirect_to root_path
    end
  end

  def set_employee
    @employee = Employee.find(params[:id])
  end

  def employee_params
    params
      .require(:employee)
      .permit(
              :name,
              :age,
              :country,
              :gender,
              :email,
              :password,
              :password_confirmation,
              user_organization_attributes: [:organization_id, :id],
              department_ids: []
              # departments_attributes: [:id, department_id: []]
              # employee_dept_attributes: [:id, :department_id]
            )
  end

end

app/controllers/superadmin/departments_controller.rb
class Superadmin::DepartmentsController < ApplicationController

  before_action :set_department, only: [:edit, :show, :update, :destroy]

  def index
    @departments = Department.all
  end

  def create
    @department = Department.new(department_params)
    if @department.save
      redirect_to superadmin_departments_path
    else
      render 'new'
    end
  end

  def new
    @department = Department.new
  end

  def edit
  end

  def update
     if @department.update_attributes(department_params)
       redirect_to superadmin_departments_path
     else
       render 'edit'
     end
   end

   def destroy
     @department.destroy
     redirect_to superadmin_departments_path
   end

   private

   def department_params
     params
      .require(:department)
      .permit(
        :name,
        admin_depts_attributes: [:department_id, :id],
        employee_depts_attributes: [:department_id, :id]
      )
   end

   def set_department
     @department = Department.find(params[:id])
   end

end

app/controllers/superadmin/employees_controller.rb
class Superadmin::EmployeesController < ApplicationController

    before_action :set_employee, only: [:edit, :show, :update, :destroy]
    # after_action :assign_default_role, only: [:create]

    def index
      @employees = Employee.all
    end

    def create
      @employee = Employee.new(employee_params)
      if @employee.save
        @employee.remove_role :admin
        @employee.add_role :employee
        redirect_to superadmin_employees_path
      else
        render 'new'
      end
    end

    def new
      @employee = Employee.new
      @employee.build_user_organization
      @employee.employee_depts.build unless @employee.present?
    end

    def edit
      @employee.build_user_organization unless @employee.user_organization.present?
    end

    def show
    end

    def update
     if @employee.update_attributes(employee_params)
       redirect_to superadmin_employees_path
     else
       render 'edit'
     end
    end

     def destroy
       @employee.destroy
       redirect_to superadmin_employees_path
     end

     def get_departments
       @departments = []
       @emp = Employee.find(params[:employee_id]) if params[:employee_id].present?
       org_id = params[:organization_id]
       organization = Organization.find(org_id)
       @departments = organization.departments if organization.present?
       # render json: @departments
       respond_to do |format|
         format.js
       end
     end
       # if organization.present?
       #   user_id = organization.user_id
       #   admin_depts = AdminDept.where(user_id: user_id)
       #   if admin_depts.present?
       #     admin_depts.each do |dept|
       #       dep_id = dept.department_id
       #       tmp_department = Department.find(dep_id)
       #       @departments << {'department_name': tmp_department.name, 'department_id':tmp_department.id}
       #     end
       #     # puts "------------------------ #{@departments}"
       #   # else
       #     # puts "-------------------------- No admin depts present"
       #   end
       # # else
       #   # puts "-------------------------- No organization present"
       # end

      #  respond_to do |format|
      #   format.js
      # end



    private

    def set_employee
      @employee = Employee.find(params[:id])
    end

    # def assign_default_role
    #   self.add_role(:employee) if self.role.blank?
    # end

    def employee_params
      params
        .require(:employee)
        .permit(
                :name,
                :age,
                :country,
                :gender,
                :email,
                :password,
                :password_confirmation,
                user_organization_attributes: [:organization_id, :id],
                department_ids: []
                # departments_attributes: [:id, department_id: []]
                # employee_dept_attributes: [:id, :department_id]
              )
    end

  end

app/controllers/superadmin/organizations_controller.rb
class Superadmin::OrganizationsController < ApplicationController

before_action :set_organization, only: [:edit, :show, :update, :destroy]

    def index
      @organizations = Organization.all
    end

    def create
      @organization = Organization.new(organization_params)
      if @organization.save
        redirect_to superadmin_organizations_path
      else
        render 'new'
      end
    end

    def new
      @organization = Organization.new
      @users = Admin.all
      @users = @users.collect {|user| [user.email, user.id] if user.admin_organization.nil?}.compact
    end

    def edit
      @users = Admin.all
      @users = @users.collect {|user| [user.email, user.id] if user.admin_organization.nil?}.compact
      puts "-----1---#{@users}------------"
      user = @organization.user
      puts "-----2---#{@organization.user}------------"
      @users << ([user.email, user.id])
        puts "----3----#{@users}------------"

    end

    def update
       if @organization.update_attributes(organization_params)
         redirect_to superadmin_organizations_path
       else
         render 'edit'
       end
     end

     def destroy
       @organization.destroy
       redirect_to superadmin_organizations_path
     end

     # def options_for_select
     #   [
     #   [user.email, user.id]
     # ]
     # end

     private

     def organization_params
       params
       .require(:organization)
       .permit(
         :user_id,
         :name,
         :address,
         :email,
         department_ids: [],
         # :organization_id
       )
     end

     def set_organization
       @organization = Organization.find(params[:id])
     end

  end

app/controllers/superadmin/users_controller.rb
class Superadmin::UsersController < ApplicationController

  before_action :authenticate_superadmin
  before_action :set_user, only: [:edit, :show, :update, :destroy]

  def index
    @users = Admin.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to superadmin_users_path
    else
      render 'new'
    end
  end

  def new
    @user = User.new
    @user.admin_depts.build
  end

  def home
      @user = User.new
  end

  def edit
  end

  def show
  end

  def update
     if @user.update(user_params)
       if @user.id == current_user.id
         redirect_to superadmin_user_path
       else
         redirect_to superadmin_users_path
       end
     else
       render 'edit'
     end
   end
     # if current_user
     #   redirect_to superadmin_home_path
     # elsif @user.update_attributes(user_update_params)
     #   redirect_to superadmin_users_path
     # else
     #   render 'edit'
     # end


     def destroy
       @user.destroy
       redirect_to superadmin_users_path
     end


  private

  def authenticate_superadmin
    unless current_user.has_role? :superadmin
      redirect_to root_path
    end
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params
      .require(:user)
      .permit(
              :name,
              :age,
              :country,
              :gender,
              :email,
              :password,
              :password_confirmation,
              department_ids: []
              # admin_depts_attributes: [:department_id, :id]
            )
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  #def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/employee/users_helper.rb
module Employee::UsersHelper
end

app/helpers/superadmin/departments_helper.rb
module Superadmin::DepartmentsHelper
end

app/helpers/superadmin/employees_helper.rb
module Superadmin::EmployeesHelper
end

app/helpers/superadmin/organizations_helper.rb
module Superadmin::OrganizationsHelper
end

app/helpers/superadmin/users_helper.rb
module Superadmin::UsersHelper
end

app/views/superadmin/users/_form.html.erb
<h1><%= @user.new_record? ? "Add Admin" : "Edit Profile" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <% button = @user.new_record? ? "Add" : "Update" %>
      <%= form_for(@user, url: @user.new_record? ? superadmin_users_path : superadmin_user_path ) do |f| %>
      <%#= render 'shared/error_messages', object: f.object %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :age %>
      <%= f.text_field :age, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :country %>
      <%= f.select :country, %w{India USA Canada}, {:prompt => 'Select'}, required: true, placeholder: 'Country', class: 'form-control' %>
    </div>

    <!-- <div class="form-group">
      <%#= f.label :organization %>
        <%# Organization.all.each do |d| %>
      <%#= f.select :organization, Organization.name, { :prompt => 'Select Organization'}, class: 'form-control' %>
       <%# (:user_id, Organization.all, :id, :name, { :prompt => 'Select a State', :selected => @email.user_id }, { class: 'form-control' }) %>
<%# end %>
    </div> -->

    <div class="form-group">
      <div class="row">
        <div class="form-group">
          <div class="col-md-12 nopadding">
            <div class="col-md-2 nopadding">
              <label class="btn">
                <%= f.label :gender, 'Gender :' %>
              </label>
            </div>
            <div class="col-md-2 nopadding">
              <label class="btn">
                <%= f.radio_button :gender, 'Male', class: 'inline-block' %>
                <%= f.label :gender, 'Male' %>
              </label>
            </div>
            <div class="col-md-2 nopadding">
              <label class="btn">
                <%= f.radio_button :gender, 'Female', class: 'inline-block' %>
                <%= f.label :gender, 'Female' %>
              </label>
            </div>
            <div class="col-md-2">
              <label class="btn">
                <%= f.radio_button :gender, 'Other', class: 'inline-block' %>
                <%= f.label :gender, 'Other' %>
              </label>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :department, "Department : " %>
        <% Department.all.each do |d| %>
          <div class="checkbox">
           <%# @user = User.find(@user.id)  %>
           <%= check_box_tag "user[department_ids][]", d.id, @user.department_ids.include?(d.id) %>
           <%= d.name %>
          </div>
        <% end %>
    </div>
        <!-- <div class="col-md-12 nopadding"> -->
          <!-- <div style="display:inline-block;" > -->
            <!-- <div class="col-md-2"> -->
              <!-- <label class="abc"> -->

                <!-- <label class="inline"> -->
                <!-- <label class="check-margin"> -->

             <!-- </label> -->
            <!-- </div> -->
          <!-- </div> -->
      <!-- </div> -->

      <%#= f.label :department, "Department : " %>
        <%#= f.fields_for :admin_depts do |a| %>
        <%#= puts "---------#{a.inspect}----------------" %>
          <%#= a.collection_check_boxes :department_id, Department.all, :id, :name do |d| %>
          <%#= a.collection_check_boxes :department_id, Department.all, :id, :name do |d| %>
            <!-- <div class="collection-check-box"> -->
              <%#= puts "---------#{d.inspect}----------------" %>
              <!-- <label> -->
              <%#= d.check_box %>
              <%#= d.label %>
            <!-- </label> -->
            <!-- </div> -->
          <%# end %>
        <%# end %>
    <%#= task_form.link_to_remove "Remove this task" %>
    <%#= f.label :remember_me, class: "checkbox inline" do %>
        <%#= f.check_box :remember_me %>
        <!-- <span>Remember Me</span> -->
      <%# end %>

    <div class="form-group">
      <%= f.label :"email" %>
      <%= f.email_field :email, class: 'form-control' %>
    </div>

    <% if @user.new_record? %>
      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, "Confirm Password" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
    <% end %>

    <div style="display:inline-block;">
    <%= f.submit button, class: "btn btn-primary btn-md" %></div>
    <%= link_to "Cancel", superadmin_users_path, class: "btn btn-primary btn-md" %>
    <% end %>
  </div>
</div>






.

app/views/superadmin/users/edit.html.erb
<%= render "superadmin/users/form" %>

app/views/superadmin/users/home.html.erb
<h1>Welcome <%= current_user.name %></h1>

app/views/superadmin/users/index.html.erb
<h1>Admin Profile</h1>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
		<p align="right"><%= link_to "New Admin", new_superadmin_user_path, class: "btn btn-primary" %></p>
		<table id="users" class="table table-hover">
			<thead class="thead-dark">
				<tr>
					<th>Name</th>
					<th>Age</th>
          <th>Country</th>
					<th>Gender</th>
          <th>Organization</th>
          <th>Department</th>
					<th>Email</th>
		      <th colspan="3">Actions</th>
		    </tr>
		  </thead>
		  <tbody>
		    <% @users.each do |user| %>
		    <tr>
		      <td><%= user.name %></td>
		      <td><%= user.age %></td>
          <td><%= user.country %></td>
		      <td><%= user.gender %></td>
          <td><%= user.admin_organization.present? ? user.admin_organization.name : "-" %></td>
          <td><%= user.departments.pluck(:name).join(' ,') %></td>
          <td><%= user.email %></td>
		      <td><%= link_to "show", superadmin_user_path(user) %></td>
		      <td><%= link_to "Edit", edit_superadmin_user_path(user) %></td>
		      <td><%= link_to "Destroy", superadmin_user_path(user), method: :delete, data: { confirm: "Are you sure?" } %></td>
		    </tr>
		    <% end %>
		  </tbody>
		</table>
	</div>
</div>

app/views/superadmin/users/new.html.erb
<%= render "superadmin/users/form" %>

app/views/superadmin/users/show.html.erb
<h1>Profile</h1>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
		<table id="users" class="table table-hover">
			<thead class="thead-dark">
				<tr>
					<th>Name</th>
					<th>Age</th>
          <th>Organization</th>
          <th>Department</th>
					<th>Country</th>
					<th>Gender</th>
					<th>Email</th>
		    </tr>
		  </thead>
		  <tbody>
		    <tr>
		      <td><%= @user.name %></td>
		      <td><%= @user.age %></td>
          <td><%= @user.organization.present? ? @user.organization.name : "-" %></td>
          <td><%= @user.departments.pluck(:name).join(' ,') %></td>
		      <td><%= @user.country %></td>
		      <td><%= @user.gender %></td>
		      <td><%= @user.email %></td>
		    </tr>
		  </tbody>
		</table>
    <p align="right"><%= link_to "Back", superadmin_users_path, class: "btn btn-primary" %></p>
	</div>
</div>